version: '3'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis
volumes:
  db-data:
