version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis
volumes:
  postgres:
